//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using DataAccessLayer.Repository;
    using System;
    using System.Collections.Generic;
    
    public partial class Claim : IEntity
    {

        public Claim()
        {
            this.Users = new HashSet<User>();
        }

        public Claim(String value)
        {
            Value = value;
            this.Users = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
