//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using DataAccessLayer.Models;
    using DataAccessLayer.Repository;
    using System;
    using System.Collections.Generic;
    
    public partial class User : IEntity 
    {

        public User()
        {
            this.ChildUsers = new HashSet<User>();
            this.Claims = new HashSet<Claim>();
        }

        [Key]
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public string Role { get; set; }
        [Required, DataType(DataType.Date)]
        public DateTime DateOfBirth { get; set; }
        [Required]
        public string Email { get; set; }
        [Required, Column(TypeName = "datetime2"), DataType(DataType.DateTime)]
        public DateTime UpdatedAt { get; set; }
        [Column(TypeName = "datetime2"), DataType(DataType.DateTime)]
        public DateTime CreatedAt { get; set; }
        //public DateTime ModifiedDate { get; set; }
        public string Location { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        [Required]
        public string PasswordSalt { get; set; }
        public Nullable<int> ParentUser_Id { get; set; }

        public String PasswordQuestion1 { get; set; }
        public String PasswordQuestion2 { get; set; }
        public String PasswordQuestion3 { get; set; }
        public String PasswordAnswer1 { get; set; }
        public String PasswordAnswer2 { get; set; }
        public String PasswordAnswer3 { get; set; }

        /// <summary>
        /// Children users below user.
        /// </summary>
        public virtual ICollection<User> ChildUsers { get; set; }
        /// <summary>
        /// Parent user above user.
        /// </summary>
        public virtual User ParentUser { get; set; }

        public virtual ICollection<Claim> Claims { get; set; }

        /// <summary>
        /// Override Equals method.  The UserName of each User is unique.
        /// </summary>
        /// <param name="obj">Another User</param>
        /// <returns>Whether Users are equal or not</returns>
        public override bool Equals(object obj)
        {
            var user = obj as User;
            if(user == null)
            {
                return false;
            }
            return UserName.Equals(user.UserName);
        }

        /// <summary>
        /// Override HashCode.  The UserName of each User is unique.
        /// </summary>
        /// <returns>UserName hashcode</returns>
        public override int GetHashCode()
        {
            return UserName.GetHashCode();
        }

        /// <summary>
        /// Override ToString.  Output username
        /// </summary>
        /// <returns>username</returns>
        public override string ToString()
        {
            return UserName;
        }
    }
}
