//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;


namespace DataAccessLayer.Models
{
    using DataAccessLayer.Models;
    using DataAccessLayer.Repository;
    using System;
    using System.Collections.Generic;
    
    public partial class User : IEntity
    {
 
        public User()
        {
            this.ChildUsers = new HashSet<User>();
            this.Claims = new HashSet<Claim>();
            CreatedAt = DateTime.UtcNow;
            Id = Guid.NewGuid();
            Disabled = false;
        }

        public User(string userName)

        {
            UserName = userName;
            this.Claims = new HashSet<Claim>();
            CreatedAt = DateTime.UtcNow;
            Id = Guid.NewGuid();
            Disabled = false;
        }

        [Key]
        public Guid Id { get; set; }

        [Required]
        public string Email { get; set; }
            
        public string UserName { get; set; }
        public string Firstname { get; set; }
        public string LastName { get; set; }
        public String CreatedDate { get; set; }
        public String HashPassword { get; set; }
        public Nullable<int> ParentUser_Id { get; set; }

        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }

        [Required, DataType(DataType.Date)]
        public DateTime? DateOfBirth { get; set; }
        [Required]
        public string PasswordHash { get; set; }
        [Required]
        public byte[] PasswordSalt { get; set; }

        [Required]
        public bool Disabled { get; set; }

        [Required, Column(TypeName = "datetime2"), DataType(DataType.DateTime)]
        public DateTime UpdatedAt { get; set; }

        [Column(TypeName = "datetime2"), DataType(DataType.DateTime)]
        public DateTime CreatedAt { get; set; }

        public string SecurityQ1 { get; set; }
        public string SecurityQ1Answer { get; set; }
        public string SecurityQ2 { get; set; }
        public string SecurityQ2Answer { get; set; }
        public string SecurityQ3 { get; set; }
        public string SecurityQ3Answer { get; set; }



        /// <summary>
        /// Children users below user.
        /// </summary>
        public virtual ICollection<User> ChildUsers { get; set; }
        /// <summary>
        /// Parent user above user.
        /// </summary>
        public virtual User ParentUser { get; set; }

        public virtual ICollection<Claim> Claims { get; set; }

        /// <summary>
        /// Override Equals method.  The UserName of each User is unique.
        /// </summary>
        /// <param name="obj">Another User</param>
        /// <returns>Whether Users are equal or not</returns>
        public override bool Equals(object obj)
        {
            var user = obj as User;
            return UserName.Equals(user.UserName);
        }

        /// <summary>
        /// Override HashCode.  The UserName of each User is unique.
        /// </summary>
        /// <returns>UserName hashcode</returns>
        public override int GetHashCode()
        {
            return UserName.GetHashCode();
        }

        /// <summary>
        /// Override ToString.  Output username
        /// </summary>
        /// <returns>username</returns>
        public override string ToString()
        {
            return UserName;
        }
    }
}
